api:
  port: 6053

esphome:
  name: lightring

logger:

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

font:
  - file: 'fonts/PragmataPro.ttf'
    id: font1
    size: 16

  - file: 'fonts/PragmataPro.ttf'
    id: font_small
    size: 12

i2c:
  scl: 4
  sda: 5
  frequency: 400kHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: ip_address
    ssid:
      name: ESP Connected SSID
      id: wifi_ssid


binary_sensor:
  - platform: status
    name: "Lightring Status"
    id: system_status
  - platform: gpio
    pin:
      number: GPIO3
      mode:
        input: true
        pullup: true
    id: btn
    filters:
      - delayed_on: 10ms
    on_click:
      min_length: 750ms
      max_length: 3000ms
      then:
        - light.toggle: builtin_led

light:
  - platform: neopixelbus
    type: GRBW
    variant: WS2812
    pin: 8
    num_leds: 24
    id: ring_led
    name: "LED ring"
  - platform: neopixelbus
    type: GRB
    variant: SK6812
    pin: 2
    num_leds: 1
    id: "builtin_led"
    name: "Built-in LED"
    restore_mode: RESTORE_DEFAULT_ON
    method:
      type: esp32_rmt
      channel: 0

display:
  - platform: ssd1306_i2c
    model: "SH1107 128x64"
    address: 0x3C
    #rotation: 90°
    lambda: |-
      it.print(0, 17, id(font_small), TextAlign::BASELINE_LEFT, "Online");
