api:
  port: 6053

esphome:
  name: screeny
  platformio_options:
      board_build.flash_mode: dio

logger:

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

external_components:
  - source: github://bekriebel/esphome@sh1107_fix
    components: [ ssd1306_base, ssd1306_i2c ]

font:
  - file: 'fonts/PragmataPro.ttf'
    id: font1
    size: 16

  - file: 'fonts/PragmataPro.ttf'
    id: font_small
    size: 12

i2c:
  scl: 18
  sda: 19

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  safe_mode: true
  password: !secret ota_password

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: ip_address
    ssid:
      name: ESP Connected SSID
      id: wifi_ssid

sensor:
  - platform: homeassistant
    id: co2_ppm
    entity_id: sensor.office_co2


light:
  - platform: neopixelbus
    type: GRB
    variant: SK6812
    pin: 2
    num_leds: 1
    id: "builtin_led"
    name: "Built-in LED"
    restore_mode: ALWAYS_ON
    method:
      type: esp32_rmt
      channel: 0

display:
  - platform: ssd1306_i2c
    model: 'SH1107_128x64'
    rotation: 90
    flip_x: false
    flip_y: false
    offset_y: 96
    offset_x: 32
    external_vcc: true
    update_interval: 1.0s
    lambda: |-
      if (id(co2_ppm).has_state()) {
        it.printf(5, 20, id(font1), "%.0f ppm", id(co2_ppm).state);
      } else {
        it.print(5, 20, id(font1), "Offline");
      }
